name: Release Extension

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Chrome Extension
        run: |
          mkdir -p dist/chrome
          cp -r chromium/* dist/chrome/
          cd dist/chrome
          zip -r chrome-extension-${{ format('{0}', github.ref_name) }}.zip .
          cd ../..

      - name: Build Firefox Extension
        run: |
          mkdir -p dist/firefox
          cp -r firefox/* dist/firefox/
          cd dist/firefox
          zip -r firefox-extension-${{ format('{0}', github.ref_name) }}.zip .
          cd ../..

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Chrome Extension
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/chrome/chrome-extension-${{ format('{0}', github.ref_name) }}.zip
          asset_name: qr-reader-chrome-extension-${{ format('{0}', github.ref_name) }}.zip
          asset_content_type: application/zip

      - name: Upload Firefox Extension
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/firefox/firefox-extension-${{ format('{0}', github.ref_name) }}.zip
          asset_name: qr-reader-firefox-extension-${{ format('{0}', github.ref_name) }}.zip
          asset_content_type: application/zip
